### ISSUE TITLE
Update environment.yml to use conda for snowflake-ml-python and streamlit

### ISSUE THREAD

**Issue by tvoipio** [Snowflake-Labs/sfguide-getting-started-dataengineering-ml-snowpark-python#20]
Conda's dependency management does not really work well if some packages are installed using pip; pip overrides whatever conda has installed in case the newest possible version which the constraints in the YAML allows has newer required dependencies.

Now it seems that Snowflake's Conda channel includes the needed streamlit and snowflake-ml-python packages, and at least the following environment resolves nicely:

```
name: snowpark-ml-lgbm
channels:
  - https://repo.anaconda.com/pkgs/snowflake
dependencies:
  - python=3.10
  - snowflake-snowpark-python>=1.4.0,<2
  - snowflake-ml-python>=1.0.0,<2
  - pandas=1.4.*
  - notebook>=6.5
  - scikit-learn=1.2.2
  - cachetools=4.2.2
  - boto3
  - pip
  - lightgbm=3.3.5
```

**Comment by iamontheinet** [comment]
@tvoipio Please use the latest version that uses Snowflake Notebooks which makes it really easy to get started.
