### ISSUE TITLE
snowflake-ml-python version not found

### ISSUE THREAD

**Issue by sfc-gh-dproksch** [Snowflake-Labs/sfguide-getting-started-dataengineering-ml-snowpark-python#4]
The version of snowflake-ml-python needs to be upgraded from 1.0.0 to 1.0.2 (as of the time of the submission).  Using conda env create --file environment.yml fails unless the version is unanchored or set to 1.0.2.

**Comment by iamontheinet** [comment]
@sfc-gh-dproksch It seems to be working for me. Can you try creating a new conda env and see which versions get installed from Snowflake Anaconda channel by default?

**Comment by iamontheinet** [comment]
@sfc-gh-dproksch FYI: environment.yml was created for Codespaces. For running everything locally, follow instructions in the QS.
