### ISSUE TITLE
snowflake-ml-python==1.0.0 is not supported for configured  python=3.9

### ISSUE THREAD

**Issue by nickorka** [Snowflake-Labs/sfguide-getting-started-dataengineering-ml-snowpark-python#5]
https://github.com/Snowflake-Labs/sfguide-getting-started-dataengineering-ml-snowpark-python/blob/47476a7f861d4402d5d5663492707db03f74dc16/environment.yml#L15

Pip subprocess output:
Collecting streamlit
  Using cached streamlit-1.24.0-py2.py3-none-any.whl (8.9 MB)

Pip subprocess error:
ERROR: Ignored the following versions that require a different python version: 0.55.2 Requires-Python <3.5
ERROR: Could not find a version that satisfies the requirement snowflake-ml-python==1.0.0 (from versions: 1.0.1, 1.0.2)
ERROR: No matching distribution found for snowflake-ml-python==1.0.0

failed

CondaEnvException: Pip failed

OS: Windows 11

**Comment by iamontheinet** [comment]
Hi @nickorka!

We have identified a bug when using Snowpark ML on Windows and we're in the process of fixing it. In the meantime, please use [Option 2 – Hex](https://quickstarts.snowflake.com/guide/getting_started_with_dataengineering_ml_using_snowpark_python/index.html?index=..%2F..index#2) to complete **Data Engineering** and **Machine Learning** sections of the QS Guide. 

Thanks for your patience and please stay tuned.

Cheers,
Dash

**Comment by iamontheinet** [comment]
Hi @nickorka! The issue has been fixed. Please let me know if you get a chance to try it out or run into any issues.
