### ISSUE TITLE
There is an issue with temporary stage

### ISSUE THREAD

**Issue by nickorka** [Snowflake-Labs/sfguide-getting-started-dataengineering-ml-snowpark-python#6]
https://github.com/Snowflake-Labs/sfguide-getting-started-dataengineering-ml-snowpark-python/blob/47476a7f861d4402d5d5663492707db03f74dc16/Snowpark_For_Python_ML.ipynb#L270

SnowparkSQLException: (1304): 01ad51d0-0503-8979-006f-c983008c8176: 002003 (02000): SQL compilation error:
Stage 'DASH_DB.DASH_SCHEMA."SNOWML_TRANSFORM_CAB1A996_1246_4696_BF17_BE65E6E11C6E	MP3YTNLBYM"' does not exist or not authorized.

Here are my packages' versions:
Successfully installed absl-py-1.4.0 aiohttp-3.8.4 aiosignal-1.3.1 altair-5.0.1 async-timeout-4.0.2 blinker-1.6.2 click-8.1.3 cryptography-38.0.4 frozenlist-1.3.3 fsspec-2023.1.0 gitdb-4.0.10 gitpython-3.1.31 markdown-it-py-3.0.0 mdurl-0.1.2 multidict-6.0.4 pillow-9.5.0 protobuf-4.23.3 pydeck-0.8.1b0 pympler-1.0.1 pytz-deprecation-shim-0.1.0.post0 pyyaml-6.0 rich-13.4.2 smmap-5.0.0 snowflake-ml-python-1.0.2 sqlparse-0.4.4 streamlit-1.24.0 tenacity-8.2.2 toml-0.10.2 toolz-0.12.0 tzdata-2023.3 tzlocal-4.3.1 validators-0.20.0 watchdog-3.0.0 xgboost-1.7.6 yarl-1.9.2

OS: Windows 11

**Comment by iamontheinet** [comment]
Hi @nickorka!

We have identified a bug when using Snowpark ML on Windows and we're in the process of fixing it. In the meantime, please use [Option 2 – Hex](https://quickstarts.snowflake.com/guide/getting_started_with_dataengineering_ml_using_snowpark_python/index.html?index=..%2F..index#2) to complete **Data Engineering** and **Machine Learning** sections of the QS Guide. 

Thanks for your patience and please stay tuned.

Cheers,
Dash

**Comment by iamontheinet** [comment]
Hi @nickorka! The issue has been fixed. Please let me know if you get a chance to try it out or run into any issues.
